SELECT MASV, HOSV, TENSV
FROM dbo.DMSV
WHERE MASV NOT IN 
(
   SELECT k.MASV
   FROM DMMH m, KETQUA k
   WHERE m.MAMH = k.MAMH and TENMH = N'Cơ sở dữ liệu'
)

SELECT MASV, MAMH, LANTHI
FROM dbo.KETQUA
WHERE MASV NOT IN 
(
   SELECT MASV 
   FROM dbo.KETQUA
   WHERE LANTHI=1 
)
and MASV IN 
(
   SELECT MASV
   FROM dbo.KETQUA
   WHERE LANTHI = 2
)


SELECT MASV,TENSV
FROM DMSV
WHERE MAKH='AV' AND NOT EXISTS (SELECT *
                                FROM KETQUA
								WHERE MAMH='05' AND
								KETQUA.MASV=DMSV.MASV)



SELECT MASV,HOSV,TENSV
FROM DMSV
WHERE MAKH='AV' AND NOT EXISTS (SELECT *
                                FROM KETQUA
								WHERE MAMH='05' AND MASV=DMSV.MASV)



SELECT MASV
FROM DMSV
WHERE NOT EXISTS ( SELECT *
                   FROM KETQUA
				   WHERE DIEM<=5 AND MASV=DMSV.MASV)



SELECT MASV,TENSV,TENKHOA
FROM DMSV,DMKHOA
WHERE NOT EXISTS (SELECT MAKH
                  FROM DMSV,KETQUA
				  WHERE PHAI=N'TRUE' AND DMSV.MASV=KETQUA.MASV  AND DMKHOA.MAKHOA=MAKH)





SELECT SV.MASV,HOSV,TENSV,SV.MAKH
FROM dbo.DMSV SV,dbo.DMKHOA K 
WHERE SV.MAKH =K.MAKHOA AND TENKHOA LIKE N'ANH VĂN' AND HOCBONG>0 
UNION 
SELECT SV.MASV,HOSV,TENSV, MAKH 
FROM dbo.DMSV SV ,dbo.KETQUA K 
WHERE SV.MASV=K.MASV AND SV.MASV NOT IN
(
  SELECT MASV FROM KETQUA WHERE DIEM<5
) 

SELECT SV.MASV, HOSV, TENSV, SV.MAKH
FROM dbo.DMSV SV
WHERE HOCBONG <= 0 
   OR EXISTS (
        SELECT 1
        FROM dbo.KETQUA K
        WHERE SV.MASV = K.MASV
        AND DIEM < 5
    )
