SELECT MAMH, TENMH, SOTIET
FROM dbo.DMMH
WHERE TENMH like 'T%'

SELECT HOSV, TENSV, PHAI
FROM dbo.DMSV
WHERE TENSV like '__i'

SELECT MAKHOA, TENKHOA
FROM dbo.DMKHOA
WHERE TENKHOA like '_N%'

SELECT HOSV, TENSV
FROM dbo.DMSV
WHERE HOSV like '%Thi%'

SELECT MASV, HOSV, TENSV, PHAI, HOCBONG
FROM dbo.DMSV
WHERE TENSV like '%[a-m]%' 

SELECT HOSV, MAKH, NOISINH, HOCBONG
FROM dbo.DMSV
WHERE NOISINH = 'Ha Noi' AND HOCBONG >= 150000

SELECT MASV, MAKH, PHAI
FROM dbo.DMSV
WHERE MAKH = 'AV' OR MAKH = 'VL'

SELECT MASV, NGAYSINH, NOISINH, HOCBONG
FROM dbo.DMSV
WHERE NGAYSINH BETWEEN '19920101' AND '19930605'

SELECT MASV, NGAYSINH, PHAI, MAKH, HOCBONG
FROM dbo.DMSV
WHERE HOCBONG BETWEEN '80000' AND '150000'

SELECT MAMH, TENMH, SOTIET
FROM dbo.DMMH
WHERE SOTIET BETWEEN '30'AND '45'

SELECT MASV, HOSV, TENSV, TENKHOA, PHAI
FROM dbo.DMSV, dbo.DMKHOA
WHERE PHAI = '0' AND (TENKHOA = 'Anh van' OR TENKHOA = 'Tin hoc')

SELECT MASV, HOSV, TENSV, PHAI, DIEM, TENMH 
FROM dbo.DMSV, dbo.KETQUA, dbo.DMMH
WHERE dbo.DMSV.MASV = dbo.KETQUA.MASV AND (dbo.DMSV.MAKH = dbo.DMKHOA.TENKHOA) and (TENMH = 'C? s? d? li?u' AND DIEM < 5)

SELECT MASV, HOSV, TENSV, TENKHOA, NOISINH, HOCBONG
FROM dbo.DMSV, dbo.DMKHOA
WHERE TENKHOA = 'Anh van' AND HOCBONG = 0
       

-- 2 sắp xếp 

SELECT HOSV, TENSV, NGAYSINH, NOISINH
FROM dbo.DMSV
ORDER BY TENSV ASC

SELECT HOSV, TENSV, NGAYSINH, NOISINH
FROM dbo.DMSV
WHERE TENSV like '%[a-m]%'
ORDER BY TENSV ASC

SELECT MASV, HOSV, TENSV, HOCBONG
FROM dbo.DMSV
ORDER BY MASV ASC

SELECT HOSV, TENSV, NGAYSINH, HOCBONG
FROM dbo.DMSV
ORDER BY NGAYSINH ASC, HOCBONG DESC

SELECT MASV, HOSV, TENSV, MAKH, HOCBONG
FROM dbo.DMSV
WHERE HOCBONG > 100000
ORDER BY MAKH DESC