INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A01', '01', '1', '3')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A01', '01', '2', '6')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A01', '02', '2', '6')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A01', '03', '1', '5')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A02', '01', '1', '4.5')


INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A02', '01', '2', '7')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A02', '03', '1', '10')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A02', '05', '1', '9')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A03', '01', '1', '2')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A03', '01', '2', '5')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A03', '03', '1', '2.5')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A03', '03', '2', '4')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('A04', '05', '2', '10')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('B01', '01', '1', '7')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('B01', '03', '1', '2.5')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('B01', '03', '2', '5')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('B02', '02', '1', '6')

INSERT dbo.KETQUA (MASV, MAMH, LANTHI, DIEM)
VALUES ('B02', '04', '1', '10')