INSERT dbo.DMKHOA(MAKHOA,TENKHOA) 
VALUES('AV', 'Anh Van')

INSERT dbo.DMKHOA(MAKHOA,TENKHOA) 
VALUES('TH','Tin hoc')

INSERT dbo.DMKHOA(MAKHOA,TENKHOA) 
VALUES('TR','Triet')

INSERT dbo.DMKHOA(MAKHOA,TENKHOA) 
VALUES('VL','Vat ly')
go


