INSERT dbo.DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG)
VALUES ('A01', 'Nguyen Thi', 'Hai', '1', ' 19930223','Ha Noi', 'TH', '130000')

INSERT dbo.DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG)
VALUES ('A02', 'Tran Van', 'Chinh', '0', '19921224','Binh Dinh', 'VL', '150000')

INSERT dbo.DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG)
VALUES ('A03', 'Le Thu Bach', 'Yen', '1', '19930221','Tp HCM', 'TH', '170000')

INSERT dbo.DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG)
VALUES ('A04', 'Tran Anh', 'Tuan', '0', '19941220','Ha noi', 'AV', '80000')

INSERT dbo.DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG)
VALUES ('B01', 'Tran Thanh', 'Mai', '1', '19930812','Hai Phong', 'TR', '0')

INSERT dbo.DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG)
VALUES ('B02', 'Tran Thi Thu', 'Thuy', '1','19940102' , 'Tp HCM','AV', '0')


