UPDATE PHONGBAN SET NgNhanChuc = '06/25/1989' WHERE MaPB = 5 

UPDATE NHANVIEN SET Luong = Luong+1000 WHERE Phong=5

DELETE FROM DIADIEM_PHONG WHERE MaPB=5 

INSERT INTO DIADIEM_PHONG VALUES(5, 'Tan Binh') 
INSERT INTO DIADIEM_PHONG VALUES(5, 'Phu Nhuan') 
INSERT INTO DIADIEM_PHONG VALUES(5, 'Thu Duc') 