CREATE DATABASE QLDUAN
GO

use QLDUAN
go

create table PHONGBAN
(
     MaPB int constraint PB_MaPB_PK PRIMARY KEY,
	 TenPB VARCHAR(10) CONSTRAINT PB_TenPB_UQ UNIQUE,
	 TrPhong CHAR (9),
	 NgNhanChuc    DATETIME default (GetDate())
)
go

CREATE TABLE NHANVIEN
(
   MaNV CHAR(9)constraint NV_MaNV_PK PRIMARY KEY,
   Ho VARCHAR(15) NOT NULL,
   TenDem VARCHAR(15),
   Ten VARCHAR(15) NOT NULL,
   NgSinh DATETIME,
   DiaChi VARCHAR(50),
   GTinh CHAR(3) constraint NV_GTinh_CK CHECK (GTinh IN ('Nam', 'Nu')),
   Luong INT,
   MaGSat CHAR(9) constraint NV_MaGSat_FK FOREIGN KEY (MaGSat) REFERENCES NHANVIEN(MaNV),
   Phong INT constraint NV_Phong_FK FOREIGN KEY (Phong) REFERENCES PHONGBAN(MaPB)
)
GO

CREATE TABLE DUAN
(
    MaDA INT constraint DUAN_MaDA_PK PRIMARY KEY,
	TenDA VARCHAR(15) NOT NULL,
	DiaDiem VARCHAR(15),
	PhongQL INT constraint DUAN_PHONGQL_FK FOREIGN KEY (PhongQL) REFERENCES PHONGBAN(MaPB)
)
GO

CREATE TABLE PHANCONG
(
   MaNV CHAR(9) NOT NULL,
   MaDA INT NOT NULL,
   SoGio DECIMAL(3,1),
   constraint PC_MaNV_MaDA_PK PRIMARY KEY (MaNV, MaDA),
   constraint PC_MaNV_FK FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
   constraint PC_MaDA_FK FOREIGN KEY (MaDA) REFERENCES DUAN(MaDA)
)
GO

CREATE TABLE THANNHAN
(
   MaNV CHAR(9) NOT NULL,
   TenTN CHAR (15) NOT NULL,
   GTinh CHAR (3) constraint TN_GTinh_CK CHECK (GTinh IN ('Nam', 'Nu')),
   NgSinh DATETIME,
   QuanHe VARCHAR(10),
   constraint TN_MaNV_TenTN_PK PRIMARY KEY (MaNV, TenTN),
   constraint TN_MaNV_FK FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV) 
)
GO

CREATE TABLE DIADIEM_PHONG
(
   MaPB INT NOT NULL,
   DiaDiem VARCHAR (15) NOT NULL,
   CONSTRAINT DD_P_MaPB_DiaDiem_PK PRIMARY KEY(MaPB, DiaDiem), 
   constraint DD_P_MaPB_PK FOREIGN KEY (MaPB) REFERENCES PHONGBAN(MaPB)
)
GO

ALTER TABLE PHONGBAN
ADD CONSTRAINT PB_TrPhong_FK FOREIGN KEY (TrPhong) REFERENCES NHANVIEN(MaNV)