USE QLDIEM 
GO

CREATE TABLE SinhVien_KetQua
(
   MASV CHAR(5),
   HOSV NVARCHAR(15),
   TENSV NVARCHAR(6),
   SOMONHOC INT
)
GO

INSERT dbo.SinhVien_KetQua (MASV, HOSV, TENSV, SOMONHOC)
VALUES ('A01', 'Nguyen Thi', 'Hai', '1')

INSERT dbo.SinhVien_KetQua (MASV, HOSV, TENSV, SOMONHOC)
VALUES ('A02', 'Tran Van', 'Chinh', '3')

INSERT dbo.SinhVien_KetQua (MASV, HOSV, TENSV, SOMONHOC)
VALUES ('A03', 'Le Thu Bach', 'Yen', '2')

INSERT dbo.SinhVien_KetQua (MASV, HOSV, TENSV, SOMONHOC)
VALUES ('A04', 'Tran Anh', 'Tuan', '2')

INSERT dbo.SinhVien_KetQua (MASV, HOSV, TENSV, SOMONHOC)
VALUES ('B01', 'Tran Thanh', 'Mai', '1')

INSERT dbo.SinhVien_KetQua (MASV, HOSV, TENSV, SOMONHOC)
VALUES ('B02', 'Tran Thi Thu', 'Thuy', '3')
GO

INSERT INTO dbo.SinhVien_KetQua (MASV, HOSV, TENSV, SOMONHOC)
SELECT s.MASV, HOSV, TENSV, COUNT(DISTINCT MAMH)
FROM dbo.DMSV s, dbo.KETQUA k
WHERE s.MASV = k.MASV
GROUP BY s.MASV, HOSV, TENSV
ALTER TABLE DMKHOA ADD SISO INT 
GO

UPDATE DMKHOA
SET SISO = (SELECT COUNT(*)
            FROM DMSV
			WHERE MAKHOA ='AV')
WHERE MAKHOA = 'AV'
GO


UPDATE DMSV
SET HOCBONG = 0
WHERE MASV IN (
      SELECT S.MASV
      FROM DMSV S,KETQUA K
	  WHERE LANTHI = 1
	  AND S.MASV = K.MASV
	  AND DIEM < 5
	  GROUP BY S.MASV
	  HAVING COUNT (S.MASV) = 2
	  )
GO


UPDATE KETQUA
SET DIEM = CASE
    WHEN DIEM < 5 AND LANTHI = 2 THEN
            CASE
                WHEN DIEM + 1 <= 5 THEN DIEM + 1
                ELSE 5
            END
       ELSE DIEM
    END
WHERE LANTHI = 2;
GO

UPDATE DMSV
SET HOCBONG = 1000000
WHERE MASV IN (
    SELECT KETQUA.MASV
    FROM dbo.KETQUA
    WHERE KETQUA.LANTHI = 1
    GROUP BY KETQUA.MASV
    HAVING AVG(KETQUA.DIEM) > 7
)
AND MASV NOT IN (
    SELECT KETQUA.MASV
    FROM KETQUA
    WHERE KETQUA.LANTHI = 1 AND KETQUA.DIEM < 5
);
go

DELETE FROM dbo.DMSV
WHERE MASV NOT IN (SELECT DISTINCT MASV FROM KETQUA)
GO

DELETE FROM dbo.DMMH
WHERE MAMH NOT IN (SELECT DISTINCT MAMH FROM KETQUA)
GO
