SELECT HOSV, TENSV, NOISINH, NGAYSINH
FROM DMSV
WHERE NOISINH LIKE N'HANOI' AND MONTH(NGAYSINH)=2

SELECT HOSV, TENSV, HOCBONG, TUOI=YEAR(GETDATE())-YEAR(NGAYSINH)
FROM DMSV
WHERE YEAR(GETDATE())-YEAR(NGAYSINH)>20 

SELECT HOSV, TENSV, TENKHOA, TUOI=YEAR(GETDATE())-YEAR(NGAYSINH)
FROM DMSV,DMKHOA
WHERE YEAR(GETDATE())-YEAR(NGAYSINH)>=20 AND YEAR(GETDATE())-YEAR(NGAYSINH)<=25

SELECT HOSV, TENSV, PHAI, NGAYSINH 
FROM DMSV
WHERE 

--2.1
SELECT MASV,PHAI,MAKH,MUCHOCBONG=CASE WHEN HOCBONG>5000 THEN 'HOCBONGCAO' ELSE 'MUCTRUNGBINH' END
FROM DMSV
--2.2
SELECT HOSV,TENSV,MAMH,LANTHI,DIEM, KETQUA=CASE WHEN DIEM < 5 THEN 'ROT' ELSE 'DAU' END
FROM DMSV, KETQUA 
WHERE DMSV.MASV= KETQUA.MASV 
--3.1
SELECT COUNT(*) AS SLSV
FROM DMSV
--3.2
Select * From ( Select COUNT(*) as 'so sv' From DMSV )A,
( Select COUNT(*) as 'so sv nu' from DMSV where phai= N'TRUE' )B
--3.3
SELECT MAKH,TENKHOA,COUNT(MASV) AS SOSV
FROM DMSV,DMKHOA
WHERE DMSV.MAKH=DMKHOA.MAKHOA
GROUP BY MAKH, TENKHOA
--3.4
SELECT MAMH,TENMH, COUNT( DISTINCT MASV) AS SOMH
FROM DMMH, DMKHOA 
GROUP BY MAMH,TENMH
--3.5
Select COUNT(*) 'Tong MH cua sinh vien', MaSV
From KETQUA
Group By MaSV
Select * From KETQUA
--3.6
Select max(HocBong) 'Max Hoc Bong', MaKH
From DMSV
Group By MaKH
Select * From DMSV
--3.7
select MAKH,'Tổng sinh viên nam'=sum(case phai when N'FALSE'then 1 else 0 end),'Tổng sinh viên nữ'=sum(case phai when N'TRUE'then 1 else 0 end)
from dmsv
group by MAKH
--3.8
Select COUNT(*) 'Tuoi', Year(NgaySinh) 'Nam'
From DMSV
Group By Year(NgaySinh)
Select * From DMSV
--3.9
SELECT TENMH,
       SUM(CASE WHEN LANTHI >= 5 THEN 1 ELSE 0 END) AS SVDAU,
       SUM(CASE WHEN LANTHI < 5 THEN 1 ELSE 0 END) AS SVROT
FROM DMMH
JOIN KETQUA ON DMMH.MAMH = KETQUA.MAMH
GROUP BY TENMH;
